### ISSUE TITLE
Cast error XML

### ISSUE THREAD

**Issue by precary** [jishi/Jishi.Intel.SonosUPnP#1]
Panagora.Sonos.Dashboard

Line 67 in MainWindow.xaml.cs 
SonosDIDL didlData = SonosDIDL.Parse(state.CurrentTrackMetaData);

Cannot implicitly convert type 'System.Collections.Generic.IList<Jishi.Intel.SonosUPnP.SonosDIDL>' to 'Jishi.Intel.SonosUPnP.SonosDIDL'.

Is there a newer Jishi.Intel.SonosUPnP ?

**Comment by jishi** [comment]
I have dumped this project in favor of the node.js based web-controller which has a full screen layout and is easier to customize.
