### ISSUE TITLE
Upnp library

### ISSUE THREAD

**Issue by HakanL** [jishi/Jishi.Intel.SonosUPnP#2]
Hello,

you have a reference to a upnp library. Where did you find this, can you post a link?

**Comment by HakanL** [comment]
Nevermind, I think I found it: http://opentools.homeip.net/dev-tools-for-upnp

**Comment by Hanno11** [comment]
Hi,
so I don't have to search where I downloaded it.
How exactly did you find me?
Greetings
Hanno

----- Ursprüngliche Nachricht -----
Von: "Hakan Lindestaf" notifications@github.com
Gesendet: ‎09.‎01.‎2015 07:19
An: "jishi/Jishi.Intel.SonosUPnP" Jishi.Intel.SonosUPnP@noreply.github.com
Betreff: Re: [Jishi.Intel.SonosUPnP] Upnp library (#2)

Nevermind, I think I found it: http://opentools.homeip.net/dev-tools-for-upnp

---

Reply to this email directly or view it on GitHub:
https://github.com/jishi/Jishi.Intel.SonosUPnP/issues/2#issuecomment-69297926=

**Comment by HakanL** [comment]
I searched some class names and found it through that, or what did you mean?

**Comment by Hanno11** [comment]
No, I mean my email

----- Ursprüngliche Nachricht -----
Von: "Hakan Lindestaf" notifications@github.com
Gesendet: ‎09.‎01.‎2015 07:43
An: "jishi/Jishi.Intel.SonosUPnP" Jishi.Intel.SonosUPnP@noreply.github.com
Cc: "Hanno" markus.hannweber@gmx.de
Betreff: Re: [Jishi.Intel.SonosUPnP] Upnp library (#2)

I searched some class names and found it through that, or what did you mean?

---

Reply to this email directly or view it on GitHub:
https://github.com/jishi/Jishi.Intel.SonosUPnP/issues/2#issuecomment-69299388=

**Comment by HakanL** [comment]
I didn't email you directly, I just created a ticket at GitHub :) Maybe you've been added to this project somehow?
